### ISSUE TITLE
[BUG] Blueprint graph event wires ignore subsystem nodes.

### ISSUE THREAD

**Issue by TobySunspear** [fpwong/BlueprintAssistWiki#126] opened 2023-05-12 00:26 UTC
When formatting a blueprint graph subsystem nodes will be properly spaced with other nodes but event wires will go straight through them.

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/112438784/e3532ade-8242-413b-a0e7-588eb7d3772e)

**Comment by fpwong** [comment] 2023-05-12 04:48
Hi TobySunspear, I believe this is not a bug. By default the setting `Treat Delegates As Execution Pins` is disabled, so that you may use the `Format all` command together with delegate pins.

Try enabling the `Treat Delegates As Execution Pins` setting and let me know if this is the behaviour you had expected.

I have had a number of questions about this, so I think I will enable this setting as default in the future.

**Comment by TobySunspear** [comment] 2023-05-12 04:51
Thanks for the reply @fpwong 

I just checked and it appears that I already have it enabled, are there any other settings I can try to verify if this is a bug?

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/112438784/1f249589-c731-4240-9eae-d2577fd8a708)

**Comment by fpwong** [comment] 2023-05-12 05:06
Thanks, I just tested this and can confirm there is some bug relating to delegate pins and collision when using the setting `Treat Delegates As Execution Pins`.

I'll try fixing this in the next update however as 5.2 has just came out, it will quite some time for me to be able to push the next update, perhaps 2 weeks or so. As a workaround for now, I would suggest you use the `Create Event` node.

**Comment by TobySunspear** [comment] 2023-05-12 05:08
I did end up using Create Event in the mean time, thanks for suggesting an alternative.

Good luck with the bug hunting and thanks for the awesome plugin!

**Comment by fpwong** [comment] 2023-06-24 02:48
Fixed in 4.2.0

**Closed as completed** 2023-06-24 02:52 UTC
Labels: bug
