### ISSUE TITLE
Inconsistent behavior of camera movement in graphs

### ISSUE THREAD

**Issue by alexander-clarke** [fpwong/BlueprintAssistWiki#123] opened 2023-04-14 13:41 UTC
Likely related to #119 fix introduced this problem.

If:
Opening up a new blueprint graph
or
Zooming in or out of a graph

and then try to move the camera, the camera move will be inconsistent and wrong

I imagine this is due to a previous completed camera movement affecting this new camera movement when it shouldn't do.
I imagine making sure a camera movement is not affected when after changing graphs or zooming in and out or the move has completed should fix this issue

Thanks!

**Comment by fpwong** [comment] 2023-04-18 04:55
Hi @alexander-clarke, yes this was caused by the previous update related to the camera movement. I should have tested this some more before pushing the update, this will be fixed in the next update.

**Comment by fpwong** [comment] 2023-04-23 02:37
Fixed in 4.1.7

**Closed as completed by fpwong** 2023-04-23 02:37 UTC
Labels: bug
